### PR TITLE
Wrapped all hard-coded text 

### PR DESCRIPTION
**Pull request by ramy-meng**
All hard-coded text is wrapped into i18n function and added into all JSON languages.

### CODE REVIEW

**Review by St3phy831 — COMMENTED** [review]
Hey, I think you were able to wrap all the hard-coded text and that you did a great job! The only concern would be that some of the text revolving the versions from package.json files were modified (I'm just wondering why). As for the hook on the equalizer.js file, I'm not sure if it does allow the translation of the text (I might be incorrect but if you saw the preset values change to the values you gave their keys then it's correct).

**Comment by odiaz95012** [comment]
I think she did that just to see if the text would actually be translated.

**Comment by odiaz95012** [comment]
She fixed it in her second pull request.

**Comment by St3phy831** [comment]
> She fixed it in her second pull request.
> […](#)

Sorry guys, I must've missed it. I should've been more thorough with my review, but thank you Oscar for letting me know! I've edited my review now.

**Pull request closed without merging**
